### ISSUE TITLE
Working with 4 models with one form.

### ISSUE THREAD

**Issue by tacomasterx** [tacomasterx/SistemaIPV_rails#1]
There are 4 models: Sale, InventoryItem, Transaction, and PaymentDeatail

When someone sells an item, it will be added to the sales queue and the `transactions table`, the `amount` at the `sales` table will be updated. To commit a sale, the user must enter a `payment` and click "Complete Sale", then the sale row will be "closed", a `payment details` row will be added and all the `inventory items` in queue will be marked as sold.

**Comment by nisnym** [comment]
Hey, can I work on this issue?

**Comment by tacomasterx** [comment]
Don't worry, I'm just learning how to use Github so I just posted a "whatever" issue based on the things I am currently learning. Anyway, thanks for the offer, if you know a method to work with multiple models/controllers in the same form I will appreciate the advice. :3
